version: '3'

services:
    postgres_bonita:
        container_name: postgres_container
        image: postgres:13
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=aspir
            - POSTGRES_USER=aspir
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - bonita-db-data:/var/lib/postgresql/data/pgdata
        networks:
            - postgres
        restart: unless-stopped


    pgadmin_bonita:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.mail
            - PGADMIN_DEFAULT_PASSWORD=secret
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        networks:
            - postgres
        restart: unless-stopped


    bonita:
        image: bonita
        ports:
            - 8080:8080
        environment:
            - POSTGRES_ENV_POSTGRES_PASSWORD=example
            - DB_VENDOR=postgres
            - DB_HOST=postgres_bonita
            - TENANT_LOGIN=tech_user
            - TENANT_PASSWORD=secret
            - PLATFORM_LOGIN=pfadmin
            - PLATFORM_PASSWORD=pfsecret
        restart: on-failure:2
        depends_on:
            - postgres_bonita
        networks:
            - postgres
        entrypoint:
            - bash
            - -c
            - |
              set -e
              echo 'Waiting for Postgres to be available'
              export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
              maxTries=10
              while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
                  let maxTries--
                  sleep 1
              done
              echo
              if [ "$$maxTries" -le 0 ]; then
                  echo >&2 'error: unable to contact Postgres after 10 tries'
                  exit 1
              fi
              exec /opt/files/startup.sh
networks:
    postgres:
        driver: bridge

volumes:
    pgadmin:
    bonita-db-data:
